networks:
  counter-net:

volumes:
  counter-vol:

services:
  web-front-end:
    build: .
    networks:
      - counter-net
    volumes:
      - type: volume
        source: counter-vol
        target: /app
    ports:
      - target: 8080  ## container port
        published: 4450  ## host port
    
  redis:
    image: "redis:alpine"
    networks:
      - counter-net
