# networks:
#   counter-net:

# volumes:
#   counter-vol:
  
# services:
#   web-fe:
#     build: .
#     command: python app.py
#     ports:
#       - target: 8080
#         published: 5001
#     networks:
#       - counter-net
#     volumes:
#       - type: volume
#         source: counter-vol
#         target: /app
#   redis:
#     image: "redis:alpine"
#     networks:
#       counter-net:







networks:
  counter-net:

volumes:
  counter-vol:

services:
  web-front-end:
    build: .
    networks:
      - counter-net
    volumes:
      - type: volume
        source: counter-vol
        target: /app
    ports:
      - target: 8080
        published: 4450
    
  redis:
    image: "redis:alpine"
    networks:
      - counter-net
